### ISSUE TITLE
iosSlider.data passing as undefined in addSlide

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#65]
this code:

``` js
var $this = $(this);
var data = $this.data('iosslider');
if(data == undefined) return false;
```

in addSlide always returns false. no matter what i pass in or modify. I reverted back to the original version 20 and it seems that the problem is still there.

**Comment by iosscripts** [comment]
Has the slider already been initialized? data only exists when $('.iosSlider').iosSlider() has been called first.

**Comment by ColColonCleaner** [comment]
Yes the slider has been initialized, and tiles are already loaded and functional. I am getting this after i have removed a tile using removeSlide, where data in that method is not undefined.

**Comment by iosscripts** [comment]
Alright I will take a look. Sorry about that :S.

**Comment by iosscripts** [comment]
Can you give me the usual JS of the slider, the initialization + the add/remove slide calls?

**Comment by iosscripts** [comment]
From email.

> Just one question. What do
> 
> return $(node).each(function() {
> 
> and
> 
> return this.each(function() {
> 
> do in the your methods?
> 
> I am modifying the add and remove slide methods so I can remove/store/reinsert tiles with their bindings intact.
> This is where I originally ran into the data=undefined problem.

**Comment by ColColonCleaner** [comment]
Sorry about the mixed up email. Thought because since it wasn't directly part of this issue i would just send an email.

**Comment by ColColonCleaner** [comment]
Also from email:

Oh one more thing, lol, I seem to be unable to directly call methods.goToSlide(1, undefined); from within a method in your code. When it hits the .each in goToSlide it just ends and doesn’t update, why is this?

Thanks for all your help.

**Comment by iosscripts** [comment]
> do in the your methods?

To put it simply, it's a workaround I found for making public methods accessible both internally by the plugin and externally through custom js. It's possible you found a bug in it :S... 

You are losing the data stored in the slider object somehow. Can you give me more info on where you are making the add/remove method calls? and the JS for those calls?

> Oh one more thing, lol, I seem to be unable to directly call methods.goToSlide(1, undefined); from within a method in your code. When it hits the .each in goToSlide it just ends and doesn’t update, why is this?

Which method?

**Comment by ColColonCleaner** [comment]
Ok this is what i am attempting to do. My app has two modes, public and private, in private mode i need to hide some tiles. It may change which ones i need to hide so i need to make it universal for all tiles. instead of writing it all outside slide i decided to try inside since you are already handling most of it it seemed.

Ok to the code:

global var in my js:

``` js
//an array for removed tiles
$.removedTiles = new Array();
```

method called from button on UI:

``` js
//Testing function for removing a tile and adding back in a different position
function removeTile(){
    //move the slider to the first tile
    $('#tileSlider_Top').iosSlider('goToSlide', 1);
    //remove the slide and capture the code/bindings
    $('#tileSlider_Top').iosSlider('removeSlide', 1);
    //call the add after 1 second
    setTimeout(function(){
        //log the tile to add, should be just object [object] in console
        //just making sure it's not null/undefined
        console.log("TILE BEFORE ADD: " + $.removedTiles[1]);
        //call addSlide with the removed tile and position 3
        $('#tileSlider_Top').iosSlider('addSlide', $.removedTiles[1], 3);
    }, 1000);
}
```

These are the modifications i made to the add/remove methods: (Also how the heck do you get your code examples to show up so well-formatted on github? i can't seem to figure out the tags for it and it's driving me nuts).

``` js
addSlide: function(slideNode, slidePosition) { 

            return this.each(function() {

                $this = $(this);
                var data = $this.data('iosslider');
                if(data == undefined) return false;

                console.log("HOLY REPLACING TILES BATMAN!: " + $.removedSlides[slidePosision]);
                if(slidePosition <= data.numberOfSlides) {
                    $(data.scrollerNode).children(':eq(' + (slidePosition - 1) + ')').before($.removedSlides[slidePosision]);
                } else {
                    $(data.scrollerNode).children(':eq(' + (slidePosition - 2) + ')').after($.removedSlides[slidePosision]);
                }

                if(activeChildOffsets[data.sliderNumber] > (slidePosition - 2)) {
                    activeChildOffsets[data.sliderNumber]++;
                }
                methods.update(this);

            });

        },

        removeSlide: function(slideNumber) {

            return this.each(function() {

                var $this = $(this);
                var data = $this.data('iosslider');
                if(data == undefined) return false;

                $.removedTiles[slideNumber] = $(data.scrollerNode).children(':eq(' + (slideNumber - 1) + ')').detach();
                console.log("TILE REMOVE: " + $.removedTiles[slideNumber]);
                if(activeChildOffsets[data.sliderNumber] > (slideNumber - 1)) {
                    activeChildOffsets[data.sliderNumber]--;
                }
                methods.update(this);

            });

        },
```

**Comment by ColColonCleaner** [comment]
Oh sorry, the first 

var $this = $(this);
var data = $this.data('iosslider');
if(data == undefined) return false;

in addSlide was just something i threw in there, it's actually out now.

The second one, inside the .each(function(){ is where the data is always undefined.

EDITED THE FIRST COMMENT TO REMOVE THE CODE

**Comment by iosscripts** [comment]
> These are the modifications i made to the add/remove methods: (Also how the heck do you get your code examples to show up so well-formatted on github? i can't seem to figure out the tags for it and it's driving me nuts).

Click edit on your 2nd to last comment above, I made a change to text around the removeTile() function to make it appear like JS.

**Comment by iosscripts** [comment]
Can I see your initialize JS - $('.iosSlider').iosSlider() - the way it appears EXACTLY in your code? I may be on to something...

Gah, nevermind. I am using your code exactly... no issues so far with undefined data. Are you doing anything else to the slider with JS?

**Comment by ColColonCleaner** [comment]
First of all thank you for that code to make js format on here. Is there a doc that i can see all the different tags?

anyway, here is the init code if it helps at all, made a couple changes, but it probably wont affect the slider:

``` js
function setupSliders(){
    //alert("starting sliders");
    if(!slidersRunning)
    {
        $('#tileSlider_Top').iosSlider({
            snapToChildren: true,
            desktopClickDrag: true,
            //navSlideSelector: '#tileSlider_Top .slideSelectors .item',
            onSlideComplete: topSlideComplete,
            onSliderLoaded: topSliderLoaded,
            onSlideChange: topSlideChange,
            frictionCoefficient: '0.96',
            snapFrictionCoefficient: '0.96',
            elasticPullResistance: '.6'
        });
        $('#tileSlider_Bottom').iosSlider({
            snapToChildren: true,
            desktopClickDrag: true,
            onSlideComplete: bottomSlideComplete,
            onSliderLoaded: bottomSliderLoaded,
            onSlideChange: bottomSlideChange,
            frictionCoefficient: '0.96',
            snapFrictionCoefficient: '0.96',
            elasticPullResistance: '.6'
        });
        slidersRunning = true;
        console.log("sliders started/restarted");
    }
}
```

just added some state variables and other confirmation stuff. so you aren't getting data=undefined? that is weird...it happens consistently on my end, i'll try moving to v22 and add my mod code back in.

**Comment by ColColonCleaner** [comment]
Um, i think your site is down.

**Comment by iosscripts** [comment]
> First of all thank you for that code to make js format on here. Is there a doc that i can see all the different tags?

No idea. I was looking for that myself and ended up finding out how the same way you did :S.

No need to move to v1.0.22, just some stuff concerning the new lock/unlock methods (unless you need those functions).

Anything odd happening in those onSlideComplete/onSliderLoaded/onSlideChange callbacks for either slider?

**Comment by iosscripts** [comment]
> Um, i think your site is down.

Should be up now. That would explain why traffic just flatlined LOL. My mac email client tries to make too many connections and blows up the server. Maybe I need a new hosting provider...

**Comment by ColColonCleaner** [comment]
Okay i have an update for you. Got back on this issue today.

Once again i'm sending you a video as that seems to help with the debugging process.

Below is the updated code i put in your addSlide and removeSlide. Attempted to move away from jquery global variables as much as possible but i still need that array.

``` js
removeSlide: function(slideNumber) {
    //loop through all elements in this object (should be just one)
    return this.each(function() {
        //capture the scope of slideNumber
        var removingSlideNumber = slideNumber;
        //get the data for this slider
        var $this = $(this);
        var data = $this.data('iosslider');
        //log the data get
        console.log("data: " + data);
        //if undefined, return
        if(data == undefined) return false;

        //set up the removed tiles array if it hasn't been done already
        if($.removedTiles==undefined)
        {
            $.removedTiles = new Array();
        }

        //get a reference to the tile being removed
        var tileRemoveRef = $(data.scrollerNode).children(':eq(' + (slideNumber - 1) + ')');
        //animate it shut and call a callback
        tileRemoveRef.animate({"width":"0"}, 1500, function(){
            //after the tile has been animated shut, detach it from the page and store in the array (after clearing it)
            $.removedTiles[removingSlideNumber] = undefined;
            $.removedTiles[removingSlideNumber] = tileRemoveRef.detach();
            //update slider using an external call
            setTimeout(function(){
                //get the ID of the slider to update
                var sliderDivToUpdate = "#" + tileRemoveRef.parent().parent().context.id;
                //call it
                $(sliderDivToUpdate).iosSlider('update');
            },0);
        });
        //update the child offsets
        if(activeChildOffsets[data.sliderNumber] > (slideNumber - 1)) {
            activeChildOffsets[data.sliderNumber]--;
        }
        //don't call update, it's done on callback of animate
        //methods.update(this);
    });
}

addSlide: function(slideNode, slidePosition) {
    //loop through all elements in this object (should be just one)
    return this.each(function() {
        //get the iosslider data for this slider
        var $this = $(this);
        var data = $this.data('iosslider');
        //log the data get
        console.log("data: " + data);
        //check if the data is undefined. if so, return.
        if(data == undefined)
        {
            return false;
        }
        //check if the tile storage array is undefined, or if the removed tile at slide number is undefined
        if($.removedTiles==undefined || $.removedTiles[slidePosition]==undefined)
        {
            //if so, use the slideNode variable to get the reinsertion tile

            //set the method of tile insert based on the slide position
            if(slidePosition <= data.numberOfSlides) {
                $(data.scrollerNode).children(':eq(' + (slidePosition - 1) + ')').before(slideNode);
            } else {
                $(data.scrollerNode).children(':eq(' + (slidePosition - 2) + ')').after(slideNode);
            }
        }
        else
        {
            //create a var to store the inserted tile's sibling
            var otherChildReference = null;

            //set the method of tile insert based on the slide position
            if(slidePosition <= data.numberOfSlides) {
                otherChildReference = $(data.scrollerNode).children(':eq(' + (slidePosition - 1) + ')')
                otherChildReference.before($.removedTiles[slidePosition]);
            } else {
                otherChildReference = $(data.scrollerNode).children(':eq(' + (slidePosition - 2) + ')')
                otherChildReference.after($.removedTiles[slidePosition]);
            }
            //animate the slide open, match the width of the sibling slide
            $.removedTiles[slidePosition].animate({"width":otherChildReference.width()}, 1500);
            //remove the reference to this loaded slide in the storage array
            $.removedTiles[slidePosition]=undefined;
        }
        //update the child offsets
        if(activeChildOffsets[data.sliderNumber] > (slidePosition - 2)) {
            activeChildOffsets[data.sliderNumber]++;
        }
        //update the slider
        methods.update(this);
    });
}
```

I no longer have any variables or references defined in my code, it's all in slider.

This was the version i made without animation, it was a lot simpler to implement, but has the same issues with inserting. Sorry, no comments on this one, lol.

``` js
removeSlide: function(slideNumber) {
    return this.each(function() {
    var $this = $(this);
    var data = $this.data('iosslider');
    if(data == undefined) return false;
        if($.removedTiles==undefined)
        {
            $.removedTiles = new Array();
        }
        $.removedTiles[slideNumber] = $(data.scrollerNode).children(':eq(' + (slideNumber - 1) + ')').detach();
        if(activeChildOffsets[data.sliderNumber] > (slideNumber - 1)) {
            activeChildOffsets[data.sliderNumber]--;
        }
        methods.update(this);
    });
},

addSlide: function(slideNode, slidePosition) {
    return this.each(function() {
        var $this = $(this);
        var data = $this.data('iosslider');
        if(data == undefined) return false;
        if($.removedTiles==undefined || $.removedTiles[slidePosition]==undefined)
        {
            if(slidePosition <= data.numberOfSlides) {
                $(data.scrollerNode).children(':eq(' + (slidePosition - 1) + ')').before(slideNode);
            } else {
                $(data.scrollerNode).children(':eq(' + (slidePosition - 2) + ')').after(slideNode);
            }
        }
        else
        {
            if(slidePosition <= data.numberOfSlides) {
                $(data.scrollerNode).children(':eq(' + (slidePosition - 1) + ')').before($.removedTiles[slidePosition]);
            } else {
                $(data.scrollerNode).children(':eq(' + (slidePosition - 2) + ')').after($.removedTiles[slidePosition]);
            }
        }
        if(activeChildOffsets[data.sliderNumber] > (slidePosition - 2)) {
            activeChildOffsets[data.sliderNumber]++;
        }
        methods.update(this);
    });
}

```

Let me know what you think.

Oh also the code i use to call add/remove:

``` js
function removeTile(){
    //remove the slide and capture the code/bindings
    $('#tileSlider_Bottom').iosSlider('removeSlide', 2);
}

function addTile(){
    //add the slide back to the slider
    $('#tileSlider_Bottom').iosSlider('addSlide', "<div>THIS TEXT SHOULD NOT APPEAR</div>", 2);
}
```

Thanks!

**Comment by ColColonCleaner** [comment]
Also you might want to get version 24 up on the main site as there was the big ipad performance fix in 24, and 20 is slow by what i remember. :)

**Comment by ColColonCleaner** [comment]
Any updates? :D?

**Comment by iosscripts** [comment]
I'll try and get you an answer tomorrow :).

**Comment by iosscripts** [comment]
Still looking into it sorry. Having trouble isolating it :S

**Comment by ColColonCleaner** [comment]
It's ok. You are seeing the same error I'm getting though right?

**Comment by iosscripts** [comment]
Yes. I have reproduced it. Uploading a fix now. :)

**Comment by iosscripts** [comment]
Try with v1.0.30. Your duplicating initialization has been resolved.

**Comment by ColColonCleaner** [comment]
Trying with version 33. The data is still coming back undefined. I basically copied and pasted my modified add/remove methods over yours, I didn't notice any changes in those methods between the old and new versions. If I am wrong please let me know.

But as of now it's still not working. With the exact same error it seems.

**Comment by iosscripts** [comment]
Ok. My fix was regarding your last video and the duplicated event errors firing on window resize. 

Just to confirm, is the undefined issue happening with the vanilla add/remove methods as well as your customized ones?

**Comment by ColColonCleaner** [comment]
Oh ok, sorry, thought i submitted a different ticket for that one lol.

But back to your point, i cant test the vanilla version under my use case. I need to store the removed elements somewhere and your code (at this time) does not allow for that. I have to do some modding so i can store and add the elements back in.

This is the code that i am using to test the semi-vanilla verison. It is the simplest set of code for which my use case is possible. The error is still happening.

``` js
addSlide:function (slideNode, slidePosition) {

            return this.each(function () {

                var $this = $(this);
                var data = $this.data('iosslider');
                if (data == undefined) return false;


                if ($.removedTiles == undefined || $.removedTiles[slidePosition] == undefined) {
                    if (slidePosition <= data.numberOfSlides) {
                        $(data.scrollerNode).children(':eq(' + (slidePosition - 1) + ')').before(slideNode);
                    } else {
                        $(data.scrollerNode).children(':eq(' + (slidePosition - 2) + ')').after(slideNode);
                    }
                }
                else {
                    if (slidePosition <= data.numberOfSlides) {
                        $(data.scrollerNode).children(':eq(' + (slidePosition - 1) + ')').before($.removedTiles[slidePosition]);
                    } else {
                        $(data.scrollerNode).children(':eq(' + (slidePosition - 2) + ')').after($.removedTiles[slidePosition]);
                    }
                }

                if (activeChildOffsets[data.sliderNumber] > (slidePosition - 2)) {
                    activeChildOffsets[data.sliderNumber]++;
                }
                methods.update(this);

            });

        },

        removeSlide:function (slideNumber) {

            return this.each(function () {

                var $this = $(this);
                var data = $this.data('iosslider');
                if (data == undefined) return false;
                if ($.removedTiles == undefined) {
                    $.removedTiles = new Array();
                }
                $.removedTiles[slideNumber] = (data.scrollerNode).children(':eq(' + (slideNumber - 1) + ')').detach();
                if (activeChildOffsets[data.sliderNumber] > (slideNumber - 1)) {
                    activeChildOffsets[data.sliderNumber]--;
                }
                methods.update(this);

            });

        },
```

**Comment by iosscripts** [comment]
When you remove 2 and are left with 3, is the touch slide functionality disabled? 

I think one of the triggers to disable the slider completely is getting picked up. This happens with the slider width is => than the width of all the slides combined. I'll keep working.

**Comment by ColColonCleaner** [comment]
Yeah i have slides at 33% width so that would be getting triggered at 3 slides.

**Comment by iosscripts** [comment]
Boom. I think I've got it. Gonna have to make some minor changes to some major functions to patch this up. Gimme a sec.

**Comment by iosscripts** [comment]
Try v1.0.36.

**Comment by ColColonCleaner** [comment]
Working in my current test case. Nice work. I'll let you know if there are any problems. :)
